runtime: nodejs18
env: standard
instance_class: F2
entrypoint: node app.js

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1

# Let App Engine handle all requests through your Node.js application
handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: "production"
  JWT_SECRET: "secret???"
  MONGO_URI: "secret???"
